#   -------------------------------------------------------------
#   Secretsmith :: Tests
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        Trivial work, not eligible to copyright
#   -------------------------------------------------------------

PYTHON=python3
RUN_TESTS_SUITE=$(PYTHON) -m unittest discover

test:
	$(RUN_TESTS_SUITE) vault/
	$(RUN_TESTS_SUITE) vault/client/
